
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (1,'cat','radio','',1,'q1');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (2,'cat','radio','',1,'q2');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (3,'cat','radio','',1,'q3');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (4,'cat','radio','',1,'q4');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (5,'cat','radio','',1,'q5');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (6,'cat','radio','',1,'q6');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (7,'cat','radio','',1,'q7');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (8,'cat','radio','',1,'q8');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (9,'daily','check','Did your shortness of breath increase?',1,'q1');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (10,'daily','check','Did your cough increase?',1,'q2');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (11,'daily','check','Did your sputum change?',1,'q3');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (12,'daily','check','Did you have chest pain or discomfort?',1,'q4');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (13,'daily','check','Did you take the same medications? Or increas',1,'q5');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (14,'daily','check','Can you do the daily work you did before?',1,'q1a');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (15,'daily','check','Can you support yourself (go to toilet, showe',1,'q1b');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (16,'daily','check','Can you walk?',1,'q1c');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (17,'daily','check','Is your sputum yellow?',1,'q3a');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (18,'daily','check','Is it green?',1,'q3b');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (19,'daily','check','Or bloody?',1,'q3c');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (20,'daily','mixed','SatoO2?',1,'satO2');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (21,'daily','mixed','Heartrate?',1,'heartRate');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (22,'daily','mixed','Temperature?',1,'temperature');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (23,'daily','mixed','PETR?',1,'petr');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (24,'daily','mixed','Walking Distance?',1,'walkingDist');
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (25,'daily','radio','How do you feel right now?',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (26,'daily','radio','How did you feel yesterday?',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (27,'ccq','radio','Short of breath at rest?',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (28,'ccq','radio','Short of breath doing physical activities?',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (29,'ccq','radio','Concerned about getting a cold or your breath',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (30,'ccq','radio','Depressed (down) because of your breathing pr',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (31,'ccq','radio','During the past week, did you cough?',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (32,'ccq','radio','During the past week, did you produce phlegm?',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (33,'ccq','radio','Limited activities due to: Strenuous physical',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (34,'ccq','radio','Limited activities due to: Moderate physical ',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (35,'ccq','radio','Limited activities due to:Daily activities at',1,NULL);
INSERT INTO `questions` (`questionId`,`category`,`type`,`text`,`active`,`label`) VALUES (36,'ccq','radio','Limited activities due to:Social activities?',1,NULL);


INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (1,1,'I never cough.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (2,1,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (3,1,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (4,1,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (5,1,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (6,1,'I cough all the time.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (7,2,'I have no phlegm in my chest at all.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (8,2,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (9,2,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (10,2,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (11,2,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (12,2,'My chest is completely full of phlegm.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (13,3,'My chest does not feel tight at all.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (14,3,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (15,3,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (16,3,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (17,3,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (18,3,'My chest feels very tight.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (19,4,'When I walk up a hill or one flight of stairs I am not breathless.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (20,4,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (21,4,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (22,4,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (23,4,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (24,4,'When I walk up a hill or one flight of stairs I am very breathless.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (25,5,'I am not limited doing any activities at home.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (26,5,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (27,5,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (28,5,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (29,5,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (30,5,'I am very limited doing activities at home.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (31,6,'I am confident leaving my home despite lung condition.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (32,6,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (33,6,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (34,6,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (35,6,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (36,6,'I am not at all confident leaving my home because od my lung condition.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (37,7,'I sleep soundly.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (38,7,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (39,7,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (40,7,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (41,7,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (42,7,'I dont sleep soundly because of my lung condition.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (43,8,'I have lots of energy.',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (44,8,'',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (45,8,'',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (46,8,'',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (47,8,'',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (48,8,'I have no energy at all.',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (49,25,'Ok',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (50,25,'Not Ok',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (51,26,'Not OK',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (52,26,'OK',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (53,27,'never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (54,27,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (55,27,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (56,27,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (57,27,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (58,27,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (59,27,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (60,28,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (61,28,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (62,28,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (63,28,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (64,28,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (65,28,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (66,28,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (67,29,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (68,29,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (69,29,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (70,29,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (71,29,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (72,29,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (73,29,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (74,30,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (75,30,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (76,30,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (77,30,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (78,30,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (79,30,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (80,30,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (81,31,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (82,31,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (83,31,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (84,31,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (85,31,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (86,31,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (87,31,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (88,32,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (89,32,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (90,32,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (91,32,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (92,32,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (93,32,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (94,32,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (95,33,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (96,33,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (97,33,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (98,33,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (99,33,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (100,33,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (101,33,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (102,34,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (103,34,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (104,34,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (105,34,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (106,34,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (107,34,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (108,34,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (109,35,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (110,35,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (111,35,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (112,35,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (113,35,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (114,35,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (115,35,'almost all the time',6);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (116,36,'Never',0);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (117,36,'hardly ever',1);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (118,36,'a few times',2);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (119,36,'several times',3);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (120,36,'many times',4);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (121,36,'a great many times',5);
INSERT INTO `answers` (`answerId`,`questionId`,`text`,`value`) VALUES (122,36,'almost all the time',6);
