#! /bin/bash
# Getting location of script
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Project root
root="$root/.."
cd "${root}"
cd tools
if [[ -z $1 ]]; then
    read -p "root user of DB: " usr
else
    usr=$1
fi
if [[ -z $2 ]]; then
    read -s -p "password: " pwd
else
    pwd=$2
fi
js=`which node`
if [[ -z $js ]]; then
  js=`which nodejs`
  if [[ -z $js ]]; then
    echo "Please install node.js"
    exit
  fi
fi
if [ ! -d "${root}/backup" ]; then
    mkdir ${root}/backup
fi
d=`date +%Y-%m-%d`
loc="${root}/backup/db_$d.dump"
$js backup.js $usr $pwd $loc
