#! /bin/bash
path=`pwd`


touch mycron
crons=`crontab -l`
if [[ -z $crons ]]; then
	echo "*/2 * * * * ${path}/res/keepAliveScript >&1" >> mycron
else
    #write out current crontab
	crontab -l > mycron
	#echo new cron into cron file
	echo "*/2 * * * * ${path}/res/keepAliveScript >&1" >> mycron
fi
crontab mycron
rm mycron
echo "Please edit your config! If you want to use SSL copy your private key and your certificate into the ssl directory in the project root."
