#! /bin/bash
path=`pwd`
output="$path/.."
nodev=`nodejs -v | grep -Po "v\d"`
if [[ -z $nodev ]]; then
    sudo apt-get install nodejs
end
sqlv=`mysql -V | grep -Po "Ver \d"`
if [[ -z $mysql ]]; then
    sudo apt-get install mysql-server
end
LS=`ls $output/config/*.example`
for file in $LS; do
    name=${file%.example}
    cp $file $name
done
cd "$output/config"
echo "Please configure your config files."
mkdir "$output/ssl"
echo "If you want to use SSL copy your private key and your certificate 
into the ssl directory in the project root."
