#! /bin/bash
# Getting location of script
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Project root
root="$root/.."
cd "${root}"
git pull
cd "tools"
js="$(which node)"
if [[ -z $1 ]]; then
    read -p "root user of DB: " usr
else
    usr=$1
fi
if [[ -z $2 ]]; then
    read -s -p "password: " pwd
else
    pwd=$2
fi
if [[ -n $js ]]; then
    node $root/tools/update.js $usr $pwd
else
    js="$(which nodejs)"
    if [[ -n $js ]]; then
        nodejs $root/tools/update.js $usr $pwd
    else
        echo "Please install node or nodejs, depending on your distribution"
    fi
fi