#! /bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root="$root/.."
LS=`ls "$root/config/*.example"`
for file in $LS; do
    cp $file "$file.bak"
done
git pull
LS2=`ls "$root/config/*.example"`
toTest=()
for file in $LS2; do
    if [ -e "$file.bak" ]; then
        output=diff $file "$file.bak"
        if [ !-z "$output" ]; then
            toTest+=$file
        fi
    else
        target=${file%.example}
        cp $file $target
        toTest+=$target
    fi
done
amount=${#toTest[@]}
if [ $amount != 0 ]; then
    text="Changes in following files: ${toTest[0]}"
    for i in [1 .. $amount]; do
        text="$text, ${toTest[$i]}"
    done
    echo text
else
    echo "Everything up to date"
fi
LS=`ls "$root/config/*.bak"`
for file in $LS; do
    rm $file
done
