#! /bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root="$root/.."
LS=`ls "$root/config/" | grep -E "example$"`
for file in $LS; do
    cp "$root/config/$file" "$root/config/$file.bak"
done
git pull origin master
LS2=`ls "$root/config/" | grep -E "example$"`
toTest=()
for file in $LS2; do
    if [ -e "$root/config/$file.bak" ]; then
        output=`diff "$root/config/$file" "$root/config/$file.bak"`
        if [ ! -z "$output" ]; then
            toTest=("${toTest[@]}" "$file")
        fi
    else
        target=${file%.example}
        cp "$root/config/$file" "$root/config/$target"
        toTest=("${toTest[@]}" "$target")
    fi
done
amount=`expr ${#toTest[@]} - 1`
if [ $amount != -1 ]; then
    echo "Changes in following files:"
    for i in `seq 0 $amount`; do
        echo ${toTest[$i]}
    done
else
    echo "Everything up to date"
fi
LS=`ls "$root/config/" | grep -E "bak$"`
for file in $LS; do
    rm "$root/config/$file"
done
pkill -u ${USER} nodejs
